# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-frosty-bread-amehziar-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_x6EyCInv7weo

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Let Spring Boot auto-detect the driver and dialect based on the URL
# Automatically create the database tables if they don't exist
spring.jpa.hibernate.ddl-auto=update

# H2 Console (will only be useful if running locally with H2)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Allow data.sql to run conditionally
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
